<a href="https://colab.research.google.com/github/Szyseba/data-sience-bootcamp/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importy

In [2]:
import numpy as np

Tablica zer

In [4]:
np.zeros(shape=(4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Tablica 4X4 wypłniona liczbą 5

In [5]:
np.full(shape=(4,4), fill_value=5,dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Tablica (lista) od do z ustalonym skokiem

In [8]:
np.arange(start=0, stop=100, step=11, dtype=int)



array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [10]:
np.arange(start=0.9, stop=1, step=0.01)


array([0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])